# -*- coding: utf-8 -*-
"""ПЗКЛ

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15sMv14OQqn4P3E9rhqyapzFccTtjPEng

**Классификация отношений между элементами аргументативной структуры**

*1. Установим необходимые библиотеки*
"""

!pip uninstall -y pyarrow datasets
!pip install pyarrow==15.0.2 datasets==2.18.0
!pip install -q sentence-transformers transformers evaluate accelerate scikit-learn

import ast
import gc
import re
import numpy as np
import pandas as pd
import random
import torch

from datasets import load_dataset, Dataset, concatenate_datasets
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
import evaluate
from sklearn.metrics import classification_report, confusion_matrix

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(42)
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

"""*2. Загрузим датасет*"""

ds_en = load_dataset("HiTZ/casimedicos-arg", "en")
ds_es = load_dataset("HiTZ/casimedicos-arg", "es")
ds_fr = load_dataset("HiTZ/casimedicos-arg", "fr")
ds_it = load_dataset("HiTZ/casimedicos-arg", "it")

print("EN:", ds_en["train"].column_names)
print("ES:", ds_es["train"].column_names)
print("FR:", ds_fr["train"].column_names)
print("IT:", ds_it["train"].column_names)

"""Здесь мы сталкиваемся с проблемой - отношения между компонентами аргументационной структуры указаны только в сабсете на английском языке.

*3. Поработаем с датасетом*
"""

def parse_py(s):
    return ast.literal_eval(s) if isinstance(s, str) else s

def normalize_ws(s: str) -> str:
    return re.sub(r"\s+", " ", s.strip())

def extract_components_from_bio(text_str: str, labels_str: str):
    """
    Возвращает список компонент (строки) в порядке появления.
    """
    tokens_segs = parse_py(text_str)     # list[list[str]]
    labels_segs = parse_py(labels_str)   # list[list[str]]
    if not isinstance(tokens_segs, list) or not isinstance(labels_segs, list):
        return []

    comps = []
    cur = []

    def flush():
        nonlocal cur
        if cur:
            comps.append(normalize_ws(" ".join(cur)))
            cur = []

    for toks, labs in zip(tokens_segs, labels_segs):
        if not isinstance(toks, list) or not isinstance(labs, list):
            flush()
            continue
        m = min(len(toks), len(labs))
        for tok, lab in zip(toks[:m], labs[:m]):
            tok = str(tok)
            if lab == "O":
                flush()
                continue
            if isinstance(lab, str) and lab.startswith("B-"):
                flush()
                cur = [tok]
            elif isinstance(lab, str) and lab.startswith("I-"):
                if cur:
                    cur.append(tok)
                else:
                    cur = [tok]
            else:
                flush()
        flush()

    return comps

embed_model = SentenceTransformer("intfloat/multilingual-e5-base")

def e5_encode(texts):
    q = [f"query: {t}" for t in texts]
    return embed_model.encode(q, normalize_embeddings=True, batch_size=64, show_progress_bar=False)

def e5_encode_passage(texts):
    p = [f"passage: {t}" for t in texts]
    return embed_model.encode(p, normalize_embeddings=True, batch_size=64, show_progress_bar=False)

def best_match_index(query_text, passages, passages_emb):
    q_emb = e5_encode([query_text])[0]                 # (d,)
    sims = passages_emb @ q_emb                        # cosine because normalized
    idx = int(np.argmax(sims))
    return idx, float(sims[idx])

def build_relations_for_doc(en_ex, tgt_ex, lang_name, sim_threshold=0.60):
    """
    Возвращает список relations для target языка в формате [[a,b,label], ...]
    """
    # EN components
    en_comps = extract_components_from_bio(en_ex["text"], en_ex["labels"])
    if len(en_comps) == 0:
        return []

    # Target components
    tgt_comps = extract_components_from_bio(tgt_ex["text"], tgt_ex["labels"])
    if len(tgt_comps) == 0:
        return []

    # embeddings for EN components once
    en_comp_emb = e5_encode_passage(en_comps)

    rels = parse_py(en_ex["relations"])  # list of [spanA, spanB, label]
    out = []

    counts_match = (len(en_comps) == len(tgt_comps))
    if not counts_match:
        tgt_comp_emb = e5_encode_passage(tgt_comps)

    for spanA, spanB, lab in rels:
        spanA = normalize_ws(str(spanA))
        spanB = normalize_ws(str(spanB))
        lab = str(lab).strip()

        i, sim_i = best_match_index(spanA, en_comps, en_comp_emb)
        j, sim_j = best_match_index(spanB, en_comps, en_comp_emb)

        # если очень слабое совпадение — пропускаем, чтобы не засорять silver labels
        if sim_i < sim_threshold or sim_j < sim_threshold:
            continue

        if counts_match and i < len(tgt_comps) and j < len(tgt_comps):
            a_t = tgt_comps[i]
            b_t = tgt_comps[j]
        else:
            # fallback: находим соответствующие компоненты прямо в target по смыслу
            a_idx, a_sim = best_match_index(en_comps[i], tgt_comps, tgt_comp_emb)
            b_idx, b_sim = best_match_index(en_comps[j], tgt_comps, tgt_comp_emb)
            if a_sim < sim_threshold or b_sim < sim_threshold:
                continue
            a_t = tgt_comps[a_idx]
            b_t = tgt_comps[b_idx]

        out.append([a_t, b_t, lab])

    return out

def add_relations_column(ds_en_split, ds_tgt_split, lang_name, sim_threshold=0.60):
    tgt_by_id = {ex["id"]: ex for ex in ds_tgt_split}

    new_rows = {"id": [], "text": [], "labels": [], "relations_gen": []}
    kept = 0
    total = 0

    for en_ex in ds_en_split:
        doc_id = en_ex["id"]
        if doc_id not in tgt_by_id:
            continue
        tgt_ex = tgt_by_id[doc_id]

        rels = build_relations_for_doc(en_ex, tgt_ex, lang_name, sim_threshold=sim_threshold)
        total += 1
        if len(rels) == 0:
            rels_str = "[]"
        else:
            kept += 1
            rels_str = str(rels)

        new_rows["id"].append(tgt_ex["id"])
        new_rows["text"].append(tgt_ex["text"])
        new_rows["labels"].append(tgt_ex["labels"])
        new_rows["relations_gen"].append(rels_str)

    print(f"[{lang_name}] docs processed: {total}, docs with >=1 relation: {kept}")
    return Dataset.from_dict(new_rows)

ds_en = load_dataset("HiTZ/casimedicos-arg", "en")
ds_es = load_dataset("HiTZ/casimedicos-arg", "es")
ds_fr = load_dataset("HiTZ/casimedicos-arg", "fr")
ds_it = load_dataset("HiTZ/casimedicos-arg", "it")

es_train = add_relations_column(ds_en["train"], ds_es["train"], "es", sim_threshold=0.60)
es_val   = add_relations_column(ds_en["validation"], ds_es["validation"], "es", sim_threshold=0.60)
es_test  = add_relations_column(ds_en["test"], ds_es["test"], "es", sim_threshold=0.60)

fr_train = add_relations_column(ds_en["train"], ds_fr["train"], "fr", sim_threshold=0.60)
fr_val   = add_relations_column(ds_en["validation"], ds_fr["validation"], "fr", sim_threshold=0.60)
fr_test  = add_relations_column(ds_en["test"], ds_fr["test"], "fr", sim_threshold=0.60)

it_train = add_relations_column(ds_en["train"], ds_it["train"], "it", sim_threshold=0.60)
it_val   = add_relations_column(ds_en["validation"], ds_it["validation"], "it", sim_threshold=0.60)
it_test  = add_relations_column(ds_en["test"], ds_it["test"], "it", sim_threshold=0.60)

print(es_train[0]["relations_gen"])

print(es_train[0]["relations_gen"])

def flatten_split(ds, rel_column, lang_name):
    rows = {"text_a": [], "text_b": [], "label": [], "lang": [], "doc_id": []}
    for ex in ds:
        rels = ast.literal_eval(ex[rel_column])
        for a, b, lab in rels:
            rows["text_a"].append(a.strip())
            rows["text_b"].append(b.strip())
            rows["label"].append(str(lab).strip())
            rows["lang"].append(lang_name)
            rows["doc_id"].append(ex["id"])
    return Dataset.from_dict(rows)

# EN
train_en = flatten_split(ds_en["train"], "relations", "en")
val_en   = flatten_split(ds_en["validation"], "relations", "en")
test_en  = flatten_split(ds_en["test"], "relations", "en")

# ES/FR/IT (используем relations_gen)
train_es = flatten_split(es_train, "relations_gen", "es")
val_es   = flatten_split(es_val, "relations_gen", "es")
test_es  = flatten_split(es_test, "relations_gen", "es")

train_fr = flatten_split(fr_train, "relations_gen", "fr")
val_fr   = flatten_split(fr_val, "relations_gen", "fr")
test_fr  = flatten_split(fr_test, "relations_gen", "fr")

train_it = flatten_split(it_train, "relations_gen", "it")
val_it   = flatten_split(it_val, "relations_gen", "it")
test_it  = flatten_split(it_test, "relations_gen", "it")

# объединяем
train_flat = concatenate_datasets([train_en, train_es, train_fr, train_it])
val_flat   = concatenate_datasets([val_en, val_es, val_fr, val_it])
test_flat  = concatenate_datasets([test_en, test_es, test_fr, test_it])

print("Train size:", len(train_flat))
print("Val size:", len(val_flat))
print("Test size:", len(test_flat))
print("Labels:", sorted(set(train_flat["label"])))

"""Проверим, верно ли модель перенесла элементы аргументативной структуры и отношения между ними в другие сабсеты."""

def show_doc_relations(doc_id, max_rel=6):
    en_ex = next(x for x in ds_en["train"] if x["id"] == doc_id)
    fr_ex = next(x for x in fr_train if x["id"] == doc_id)

    en_rels = ast.literal_eval(en_ex["relations"])
    fr_rels = ast.literal_eval(fr_ex["relations_gen"])

    print("="*120)
    print("DOC:", doc_id)
    print(f"EN relations: {len(en_rels)} | FR relations_gen: {len(fr_rels)}")
    print("-"*120)

    k = min(max_rel, len(en_rels), len(fr_rels))
    for i in range(k):
        a_en, b_en, lab_en = en_rels[i]
        a_fr, b_fr, lab_fr = fr_rels[i]

        print(f"[{i}] LABEL EN={lab_en} | FR={lab_fr}")
        print("EN A:", a_en.strip())
        print("FR A:", a_fr.strip())
        print("EN B:", b_en.strip())
        print("FR B:", b_fr.strip())
        print("-"*120)

from sentence_transformers import util

def show_doc_relations_matched(doc_id, max_rel=6):
    en_ex = next(x for x in ds_en["train"] if x["id"] == doc_id)
    fr_ex = next(x for x in fr_train if x["id"] == doc_id)

    en_rels = ast.literal_eval(en_ex["relations"])
    fr_rels = ast.literal_eval(fr_ex["relations_gen"])

    print("="*120)
    print("DOC:", doc_id)
    print(f"EN relations: {len(en_rels)} | FR relations_gen: {len(fr_rels)}")

    en_texts = [f"{a.strip()} || {b.strip()}" for a,b,_ in en_rels]
    fr_texts = [f"{a.strip()} || {b.strip()}" for a,b,_ in fr_rels]

    en_emb = embed_model.encode([f"query: {t}" for t in en_texts], normalize_embeddings=True)
    fr_emb = embed_model.encode([f"passage: {t}" for t in fr_texts], normalize_embeddings=True)

    sim = en_emb @ fr_emb.T

    used_fr = set()
    shown = 0

    for i in range(len(en_rels)):
        if shown >= max_rel:
            break

        best_j = None
        best_s = -1
        for j in np.argsort(-sim[i]):
            j = int(j)
            if j in used_fr:
                continue
            best_j = j
            best_s = float(sim[i, j])
            break

        if best_j is None:
            continue

        a_en, b_en, lab_en = en_rels[i]
        a_fr, b_fr, lab_fr = fr_rels[best_j]
        used_fr.add(best_j)

        print("-"*120)
        print(f"Match sim={best_s:.3f} | LABEL EN={lab_en} FR={lab_fr}")
        print("EN A:", a_en.strip())
        print("FR A:", a_fr.strip())
        print("EN B:", b_en.strip())
        print("FR B:", b_fr.strip())

        shown += 1

fr_ids_with_rels = []
for ex in fr_train:
    rels = ast.literal_eval(ex["relations_gen"])
    if len(rels) > 0:
        fr_ids_with_rels.append(ex["id"])

print("Docs with >=1 FR relation:", len(fr_ids_with_rels))

for doc_id in random.sample(fr_ids_with_rels, 3):
    show_doc_relations_matched(doc_id, max_rel=5)

"""По выведенным примерам видно, что элементы структуры и метки отношений перенесены адекватно. Теперь можно приступать к обучению модели на подготовленном датасете.

Пример из датасета
"""

example = ds_en["train"][0]
print(example)

"""*4. Загрузим модель*"""

from transformers import pipeline

pipe = pipeline("fill-mask", model="FacebookAI/xlm-roberta-base")

label_list = sorted(set(train_flat["label"]))
label2id = {lab: i for i, lab in enumerate(label_list)}
id2label = {i: lab for lab, i in label2id.items()}
print("label2id:", label2id)

def add_numeric_label(ex):
    ex["labels"] = label2id[ex["label"]]
    return ex

train_flat2 = train_flat.map(add_numeric_label)
val_flat2   = val_flat.map(add_numeric_label)
test_flat2  = test_flat.map(add_numeric_label)

model_name = "xlm-roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

MAX_LEN = 128

def tokenize_batch(batch):
    return tokenizer(
        batch["text_a"],
        batch["text_b"],
        truncation=True,
        padding="max_length",
        max_length=MAX_LEN
    )

remove_cols = ["text_a", "text_b", "label", "lang", "doc_id"]

train_tok = train_flat2.map(tokenize_batch, batched=True, remove_columns=remove_cols)
val_tok   = val_flat2.map(tokenize_batch, batched=True, remove_columns=remove_cols)
test_tok  = test_flat2.map(tokenize_batch, batched=True, remove_columns=remove_cols)

train_tok.set_format("torch")
val_tok.set_format("torch")
test_tok.set_format("torch")

"""Добавим предобучение на нескольких текстах (возможно, придется добавлять больше текстов))"""

unlabeled_texts = [
    "Like many other problems of today, that of cardiovascular diseases is becoming more and more urgent as far as young people are concerne d. Congenital malformations are an obvious paediatric problem. Rheumatic fever and rheumatic heart disease, particularly in hot areas where there is overcrowding and wher e hygienic measures are inadequate, and cardiomyopathies of infectious, parasitic and unknown causes, occur mainly in youth. Hyperte nsion resulting from g lomc rulonephritis or pyelonephritis usually has its roots in childhood. Atherosclerosis in some vessels also begins in childhood, although its most serious complications in the heart and brain usually become manifest in middle age. The present possib ilities for prevention and control at the level of the community are shown in table 1. Enough knowledge already exists for the effective control and prevention of rheumatic heart disease, chronic car pulmonale and heart diseases connected with infections. Essential hypertension can b e effi cie ntly controlled so that its serious complications, such as hypertensive heart disease and cerebrovascular disease, are reduced. Although it is not yet possible to rr e vent the occurrence of ischaemic heart di SP, as e e r peripher a l vascul a r dis e ases of atheroscle rotic origin, t imely tr eatment a nd rehabilitation of subjects with acute myocardial infarction a llows the majority to r e sume previous life activities. These possib\lities are well known and have been summarized also in WHO publications. However, they have not bee n applied adequately in many areas wher e these conditions are common. ",
    "Radical treatment of precancerous conditions is often possible, but in other cases it may be difficult to r e move the lesion completely. Also, the carcinogenic process may continue to act after the precancerous lesion has been removed. This is frequently seen in lesions such as leukoplasias of the mouth and papillomas of the bladder. Patients with definite precancerous conditions should therefore be followed up for a considerable period of time and properly registered, preferably by a national cancer registry. ",
    "Los exámenes de aspirado de médula ósea (MO) muestran un sistema megacariopoyético íntegro o hiperplástico compatible con destrucción plaquetaria periférica, y al igual que en la púrpura trombocitopénica idiopática (PTI), se plantea que los anticuerpos antipla-quetarios, así como el secuestro y destrucción de las plaquetas en el bazo son los responsables de la trombopenia,6 ya que en pacientes afectados con rubéola, influenza y vaccinia se reporta la unión de los virus a las plaquetas de sangre periférica (SP).",
    "Ocurren principalmente en las arterias lenticuloestriadas y talamoperforantes. Aunque se han descrito por lo menos 20 síndromes lacunares, los 5 más frecuentes son: hemiparesia motora pura, síndrome sensitivo puro, síndrome sensitivo-motor, disartria-mano torpe y hemiparesia atáxica. Los principales factores de riesgo asociados a IL son hipertensión arterial (HAS) y diabetes mellitus17-19.Los hallazgos que apoyan la enfermedad de pequeño vaso son: a) síndrome lacunar, b) historia de diabetes o HAS, c) IC menor de 1.5 cm localizado en estructuras profundas y, c) exclusión de otras causas",
    "L’attuale incremento dell’incidenza di diverse patologie a trasmissione sessuale (sifilide, gonorrea, infezione da Chlamydia e, probabilmente, anche infezioni da Herpes e papilloma virus) osservato in alcuni Paesi dell’Unione Europea e comparso dopo un periodo di oltre un decennio in cui l’incidenza era fortemente diminuita, avviene in un contesto di aumento della trasmissione eterosessuale dell’HIV e della prevalenza dell’infezione stessa, in conseguenza della sempre più estesa applicazione della terapia antiretrovirale, che ha aumentato sensibilmente la sopravvivenza dei soggetti affetti da tale patologia.",
    "Fra le malattie infettive di maggiore risalto in ambito occupazionale si ricordano le zoonosi, quali la brucellosi, le rickettsiosi, la leishmaniosi, l’echinococcosi, particolarmente endemiche nelle regioni centro-meridionali italiane, ed altre meno diffuse, ma non trascurabili, quali la borreliosi di Lyme, frequente nelle regioni settentrionali, la febbre Q, la leptospirosi, la tubercolosi da Mycobacterium tuberculosis Avium e Bovis, l’afta epizootica.",
    "Selon une étude récente, les maladies les plus invalidantes en Belgique sont, par ordre décroissant d’importance : les maladies de l’appareil locomoteur, dont les maux de dos et les douleurs cervicales ; les conséquences d’accidents ; la dépression ; le diabète ; la migraine et la bronchite chronique ",
    "Une maladie auto-immune peut se définir par l'activation du système immunitaire du patient contre ses propres antigènes. Les lymphocytes T et B autoréactifs activés vont entraîner la destruction des propres constituants de l'individu via plusieurs mécanismes, soit directement par les lymphocytes T cytotoxiques ou par les dépôts d'anticorps activant le système du complément, soit indirectement via l'activation d'autres cellules impliquées dans la réponse inflammatoire comme au cours des atteintes rénales du lupus. ",

]

from transformers import AutoTokenizer

model_name = "xlm-roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=256
    )

from datasets import Dataset

dataset = Dataset.from_dict({"text": unlabeled_texts})
tokenized_dataset = dataset.map(tokenize_function, batched=True, remove_columns=["text"])

from transformers import DataCollatorForLanguageModeling

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=True,
    mlm_probability=0.15
)

"""Сохраняем предобученную модель"""

from transformers import AutoModelForMaskedLM

model = AutoModelForMaskedLM.from_pretrained(model_name)

from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir="./xlmr-medical-mlm",
    num_train_epochs=3,
    per_device_train_batch_size=4,
    save_steps=10000,
    save_total_limit=2,
    logging_steps=500,
    learning_rate=5e-5,
    weight_decay=0.01,
    fp16=True
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    data_collator=data_collator
)

trainer.train()

trainer.save_model("./xlmr-medical-adapted")
tokenizer.save_pretrained("./xlmr-medical-adapted")

model_name = "./xlmr-medical-adapted"

"""Посмотрим на работу baseline модели для вычисления эффективности fine-tune настройки"""

baseline_model_name = "xlm-roberta-base"

from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer
import evaluate
from sklearn.metrics import classification_report
import numpy as np

baseline_model_name = "xlm-roberta-base"

baseline_model = AutoModelForSequenceClassification.from_pretrained(
    baseline_model_name,
    num_labels=len(label2id),
    id2label=id2label,
    label2id=label2id
)

accuracy = evaluate.load("accuracy")
f1 = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)

    metrics = {
        "accuracy": accuracy.compute(predictions=preds, references=labels)["accuracy"],
        "f1_macro": f1.compute(predictions=preds, references=labels, average="macro")["f1"],
    }

    report = classification_report(
        labels,
        preds,
        target_names=[id2label[i] for i in range(len(id2label))],
        digits=4,
        zero_division=0,
        output_dict=True
    )

    if "Attack" in report:
        metrics["attack_precision"] = report["Attack"]["precision"]
        metrics["attack_recall"] = report["Attack"]["recall"]
        metrics["attack_f1"] = report["Attack"]["f1-score"]

    if "Support" in report:
        metrics["support_precision"] = report["Support"]["precision"]
        metrics["support_recall"] = report["Support"]["recall"]
        metrics["support_f1"] = report["Support"]["f1-score"]

    return metrics

baseline_training_args = TrainingArguments(
    output_dir="./xlmr_baseline_clean",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    num_train_epochs=3,
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    logging_steps=100,
    report_to="none",
    save_total_limit=1,
    seed=42
)

baseline_trainer = Trainer(
    model=baseline_model,
    args=baseline_training_args,
    train_dataset=train_tok,
    eval_dataset=val_tok,
    compute_metrics=compute_metrics
)

baseline_trainer.train()

from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

baseline_pred = baseline_trainer.predict(test_tok)

y_true = baseline_pred.label_ids
y_pred = np.argmax(baseline_pred.predictions, axis=-1)

baseline_metrics = compute_metrics((baseline_pred.predictions, baseline_pred.label_ids))
print("Baseline test metrics:\n")
print(baseline_metrics)

print("\nClassification report:\n")
print(classification_report(
    y_true,
    y_pred,
    target_names=[id2label[i] for i in range(len(id2label))],
    digits=4,
    zero_division=0
))

class_names = [id2label[i] for i in range(len(id2label))]
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(5, 4))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap=sns.light_palette("pink", as_cmap=True),
    xticklabels=class_names,
    yticklabels=class_names
)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Baseline Confusion Matrix")
plt.tight_layout()
plt.show()

baseline_results = baseline_metrics.copy()
print(baseline_results)

"""Теперь приступим непосредственно к fine-tune. Вначале посмотрим, насколько улучшится результат с учётом предобучения на релевантных текстах."""

from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer
import evaluate

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=len(label2id),
    id2label=id2label,
    label2id=label2id
)

accuracy = evaluate.load("accuracy")
f1 = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)

    metrics = {
        "accuracy": accuracy.compute(predictions=preds, references=labels)["accuracy"],
        "f1_macro": f1.compute(predictions=preds, references=labels, average="macro")["f1"],
    }

    report = classification_report(
        labels,
        preds,
        target_names=[id2label[i] for i in range(len(id2label))],
        digits=4,
        zero_division=0,
        output_dict=True
    )

    if "Attack" in report:
        metrics["attack_precision"] = report["Attack"]["precision"]
        metrics["attack_recall"] = report["Attack"]["recall"]
        metrics["attack_f1"] = report["Attack"]["f1-score"]

    if "Support" in report:
        metrics["support_precision"] = report["Support"]["precision"]
        metrics["support_recall"] = report["Support"]["recall"]
        metrics["support_f1"] = report["Support"]["f1-score"]

    return metrics

import transformers, inspect
from transformers import TrainingArguments

print("transformers version:", transformers.__version__)

params = inspect.signature(TrainingArguments.__init__).parameters
print("supports evaluation_strategy:", "evaluation_strategy" in params)
print("supports eval_strategy:", "eval_strategy" in params)
print("supports save_strategy:", "save_strategy" in params)
print("supports load_best_model_at_end:", "load_best_model_at_end" in params)
print("supports metric_for_best_model:", "metric_for_best_model" in params)
print("supports warmup_ratio:", "warmup_ratio" in params)

import transformers, inspect
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./xlmr_multilingual_baseline",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    num_train_epochs=3,
    weight_decay=0.01,
    warmup_ratio=0.06,
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    logging_steps=100,
    report_to="none",
     save_total_limit=1,
    seed=42
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tok,
    eval_dataset=val_tok,
    compute_metrics=compute_metrics
)
trainer.train()

"""Проведём проверку на тестовых данных."""

test_output = trainer.predict(test_tok)

from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pred_output = trainer.predict(test_tok)

y_true = pred_output.label_ids
y_pred = np.argmax(pred_output.predictions, axis=-1)

test_metrics = compute_metrics((pred_output.predictions, pred_output.label_ids))
print("Test metrics:\n")
print(test_metrics)

print("\nClassification report:\n")
print(classification_report(
    y_true,
    y_pred,
    target_names=[id2label[i] for i in range(len(id2label))],
    digits=4,
    zero_division=0
))

class_names = ['Attack', 'Support']

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(5, 4))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap=sns.light_palette("pink", as_cmap=True),
    xticklabels=class_names,
    yticklabels=class_names
)
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""Результаты работы предобученной модели показали небольшой прирост метрик. Продолжим настройку модели.

Добавим взвешенную функцию потерь, чтобы справиться с дисбалансом классов.

Посчитаем веса классов.
"""

import torch.nn as nn
from transformers import Trainer
from collections import Counter

y_train = np.array(train_tok["labels"])
class_counts = Counter(y_train)

print("Class counts:", class_counts)
print("id2label:", id2label)

num_classes = len(id2label)
total_samples = len(y_train)

class_weights = torch.tensor(
    [total_samples / (num_classes * class_counts[i]) for i in range(num_classes)],
    dtype=torch.float
)

print("Class weights:", class_weights)

"""Задаём новую функцию обучения."""

import torch.nn as nn
from transformers import Trainer

class WeightedTrainer(Trainer):
    def __init__(self, class_weights=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.class_weights = class_weights

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits

        loss_fct = nn.CrossEntropyLoss(
            weight=self.class_weights.to(logits.device)
        )
        loss = loss_fct(logits, labels)

        return (loss, outputs) if return_outputs else loss

"""Создадим копию модели для обучения."""

from transformers import AutoModelForSequenceClassification

model_weighted = AutoModelForSequenceClassification.from_pretrained(
    "./xlmr-medical-adapted",
    num_labels=len(label2id),
    id2label=id2label,
    label2id=label2id
)

from transformers import TrainingArguments

training_args_weighted = TrainingArguments(
    output_dir="./xlmr_weighted",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    warmup_steps=150,
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    logging_steps=100,
    report_to="none",
)

trainer_weighted = WeightedTrainer(
    class_weights=class_weights,
    model=model_weighted,
    args=training_args_weighted,
    train_dataset=train_tok,
    eval_dataset=val_tok,
    compute_metrics=compute_metrics
)

trainer_weighted.train()

"""Посмотрим, улучшилось ли качество обработки после добавления взвешенной функции потерь."""

from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

test_metrics_weighted = trainer_weighted.predict(test_tok)
print("Weighted test metrics:", test_metrics_weighted)

pred_output = trainer_weighted.predict(test_tok)
y_true = pred_output.label_ids
y_pred = np.argmax(pred_output.predictions, axis=1)

print("\nClassification report:\n")
print(classification_report(
    y_true,
    y_pred,
    target_names=[id2label[i] for i in range(len(id2label))]
))

class_names = ['Attack', 'Support']

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(5, 4))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap=sns.light_palette("pink", as_cmap=True),
    xticklabels=class_names,
    yticklabels=class_names
)
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""Взвешенная функция потерь дала прирост по метрикам и позволила модели увереннее выбирать класс Attack. Однако мы видим, что несколько отношений, для которых верно прдесказывался класс Support, перешли в класс Attack. Попробуем исправить это, подобрав threshold, т.е. порог модели для принятия решения о проставлении метки класса."""

from scipy.special import softmax
from sklearn.metrics import classification_report, precision_recall_fscore_support, accuracy_score
import pandas as pd
import numpy as np

# Предсказания на validation
val_output = trainer_weighted.predict(val_tok)

y_val_true = val_output.label_ids
val_probs = softmax(val_output.predictions, axis=1)

attack_id = label2id["Attack"]
support_id = label2id["Support"]

attack_probs = val_probs[:, attack_id]

results = []

thresholds = np.arange(0.1, 0.91, 0.05)

for threshold in thresholds:
    y_val_pred = np.where(attack_probs >= threshold, attack_id, support_id)

    precision_arr, recall_arr, f1_arr, _ = precision_recall_fscore_support(
        y_val_true,
        y_val_pred,
        labels=[attack_id, support_id],
        zero_division=0
    )

    acc = accuracy_score(y_val_true, y_val_pred)

    results.append({
        "threshold": threshold,
        "accuracy": acc,
        "attack_precision": precision_arr[0],
        "attack_recall": recall_arr[0],
        "attack_f1": f1_arr[0],
        "support_precision": precision_arr[1],
        "support_recall": recall_arr[1],
        "support_f1": f1_arr[1],
        "macro_f1": (f1_arr[0] + f1_arr[1]) / 2
    })

threshold_df = pd.DataFrame(results).sort_values("macro_f1", ascending=False)

print("Top thresholds on validation:")
display(threshold_df.head(10))

"""Выбираем новый threshold - 0,3. Обучим модель с новым threshold и оценим полученные результаты."""

best_threshold = 0.3

from scipy.special import softmax
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_recall_fscore_support
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Предсказания на test
test_output = trainer_weighted.predict(test_tok)

y_true = test_output.label_ids
test_probs = softmax(test_output.predictions, axis=1)

attack_id = label2id["Attack"]
support_id = label2id["Support"]

# Применяем найденный threshold
attack_probs_test = test_probs[:, attack_id]
y_pred = np.where(attack_probs_test >= best_threshold, attack_id, support_id)

# Текстовый отчёт
print(f"Threshold on test: {best_threshold:.2f}\n")

print("Classification report with threshold:\n")
print(classification_report(
    y_true,
    y_pred,
    target_names=[id2label[i] for i in range(len(id2label))],
    digits=4,
    zero_division=0
))

# Отдельные метрики
precision_arr, recall_arr, f1_arr, _ = precision_recall_fscore_support(
    y_true,
    y_pred,
    labels=[attack_id, support_id],
    zero_division=0
)

acc = accuracy_score(y_true, y_pred)
macro_f1 = (f1_arr[0] + f1_arr[1]) / 2

print("Summary metrics:")
print({
    "accuracy": acc,
    "attack_precision": precision_arr[0],
    "attack_recall": recall_arr[0],
    "attack_f1": f1_arr[0],
    "support_precision": precision_arr[1],
    "support_recall": recall_arr[1],
    "support_f1": f1_arr[1],
    "macro_f1": macro_f1
})

# Матрица ошибок
cm = confusion_matrix(y_true, y_pred)

class_names_ru = ["Attack", "Support"]

plt.figure(figsize=(5, 4))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap=sns.light_palette("pink", as_cmap=True),
    xticklabels=class_names_ru,
    yticklabels=class_names_ru
)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title(f"Confusion matrix, threshold = {best_threshold:.2f}")
plt.tight_layout()
plt.show()

"""Также мы хотим сравнить работу нашей модели и работу BERT multilingual base model (cased) от Google."""

from transformers import AutoTokenizer, AutoModelForMaskedLM
from datasets import Dataset

model_name_mbert = "google-bert/bert-base-multilingual-cased"

tokenizer_mbert = AutoTokenizer.from_pretrained(model_name_mbert)
model_mbert_mlm = AutoModelForMaskedLM.from_pretrained(model_name_mbert)

dataset_mbert_mlm = Dataset.from_dict({"text": unlabeled_texts})
dataset_mbert_mlm

def tokenize_function_mbert_mlm(batch):
    return tokenizer_mbert(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=MAX_LEN
    )

tokenized_dataset_mbert_mlm = dataset_mbert_mlm.map(
    tokenize_function_mbert_mlm,
    batched=True,
    remove_columns=["text"]
)

from transformers import DataCollatorForLanguageModeling

data_collator_mbert = DataCollatorForLanguageModeling(
    tokenizer=tokenizer_mbert,
    mlm=True,
    mlm_probability=0.15
)

from transformers import TrainingArguments, Trainer

training_args_mbert_mlm = TrainingArguments(
    output_dir="./mbert-medical-mlm",
    num_train_epochs=3,
    per_device_train_batch_size=4,
    save_steps=10000,
    save_total_limit=2,
    logging_steps=100,
    learning_rate=5e-5,
    weight_decay=0.01,
    fp16=True,
    report_to="none"
)

trainer_mbert_mlm = Trainer(
    model=model_mbert_mlm,
    args=training_args_mbert_mlm,
    train_dataset=tokenized_dataset_mbert_mlm,
    data_collator=data_collator_mbert
)

trainer_mbert_mlm.train()

trainer_mbert_mlm.save_model("./mbert-medical-adapted")
tokenizer_mbert.save_pretrained("./mbert-medical-adapted")

from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_name_mbert = "./mbert-medical-adapted"

tokenizer_mbert = AutoTokenizer.from_pretrained(model_name_mbert)

model_mbert = AutoModelForSequenceClassification.from_pretrained(
    model_name_mbert,
    num_labels=len(label2id),
    id2label=id2label,
    label2id=label2id
)

def tokenize_function_mbert(batch):
    return tokenizer_mbert(
        batch["text_a"],
        batch["text_b"],
        truncation=True,
        padding="max_length",
        max_length=MAX_LEN
    )

remove_cols = ["text_a", "text_b", "label", "lang", "doc_id"]

train_tok_mbert = train_flat2.map(
    tokenize_function_mbert,
    batched=True,
    remove_columns=remove_cols
)
val_tok_mbert = val_flat2.map(
    tokenize_function_mbert,
    batched=True,
    remove_columns=remove_cols
)
test_tok_mbert = test_flat2.map(
    tokenize_function_mbert,
    batched=True,
    remove_columns=remove_cols
)

train_tok_mbert.set_format("torch")
val_tok_mbert.set_format("torch")
test_tok_mbert.set_format("torch")

from transformers import TrainingArguments

training_args_mbert = TrainingArguments(
    output_dir="./mbert_weighted",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    logging_steps=100,
    report_to="none",
    save_total_limit=1,
    seed=42,
    fp16=True
)

trainer_weighted_mbert = WeightedTrainer(
    class_weights=class_weights,
    model=model_mbert,
    args=training_args_mbert,
    train_dataset=train_tok_mbert,
    eval_dataset=val_tok_mbert,
    compute_metrics=compute_metrics
)

trainer_weighted_mbert.train()

from scipy.special import softmax
from sklearn.metrics import precision_recall_fscore_support, accuracy_score
import pandas as pd
import numpy as np

# Предсказания на validation
val_output_mbert = trainer_weighted_mbert.predict(val_tok_mbert)

y_val_true_mbert = val_output_mbert.label_ids
val_probs_mbert = softmax(val_output_mbert.predictions, axis=1)

attack_id = label2id["Attack"]
support_id = label2id["Support"]

attack_probs_mbert = val_probs_mbert[:, attack_id]

results_mbert = []
thresholds = np.arange(0.1, 0.91, 0.05)

for threshold in thresholds:
    y_val_pred_mbert = np.where(
        attack_probs_mbert >= threshold,
        attack_id,
        support_id
    )

    precision_arr, recall_arr, f1_arr, _ = precision_recall_fscore_support(
        y_val_true_mbert,
        y_val_pred_mbert,
        labels=[attack_id, support_id],
        zero_division=0
    )

    acc = accuracy_score(y_val_true_mbert, y_val_pred_mbert)

    results_mbert.append({
        "threshold": threshold,
        "accuracy": acc,
        "attack_precision": precision_arr[0],
        "attack_recall": recall_arr[0],
        "attack_f1": f1_arr[0],
        "support_precision": precision_arr[1],
        "support_recall": recall_arr[1],
        "support_f1": f1_arr[1],
        "macro_f1": (f1_arr[0] + f1_arr[1]) / 2
    })

threshold_df_mbert = pd.DataFrame(results_mbert).sort_values(
    ["attack_f1", "attack_precision"],
    ascending=False
)

print("Top thresholds for mBERT on validation:")
display(threshold_df_mbert.head(10))

best_threshold_mbert = threshold_df_mbert.iloc[0]["threshold"]
print("Best threshold for mBERT:", best_threshold_mbert)
print(threshold_df_mbert.iloc[0])

from scipy.special import softmax
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_recall_fscore_support
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# ВРУЧНУЮ меняешь здесь
manual_threshold = 0.4

# Предсказания на test
test_output_mbert = trainer_weighted_mbert.predict(test_tok_mbert)

y_true_mbert = test_output_mbert.label_ids
test_probs_mbert = softmax(test_output_mbert.predictions, axis=1)

attack_id = label2id["Attack"]
support_id = label2id["Support"]

attack_probs_test_mbert = test_probs_mbert[:, attack_id]

y_pred_mbert = np.where(
    attack_probs_test_mbert >= manual_threshold,
    attack_id,
    support_id
)

print(f"Manual threshold for mBERT: {manual_threshold:.2f}\n")

print("Classification report for mBERT:\n")
print(classification_report(
    y_true_mbert,
    y_pred_mbert,
    target_names=[id2label[i] for i in range(len(id2label))],
    digits=4,
    zero_division=0
))

precision_arr_mbert, recall_arr_mbert, f1_arr_mbert, _ = precision_recall_fscore_support(
    y_true_mbert,
    y_pred_mbert,
    labels=[attack_id, support_id],
    zero_division=0
)

mbert_summary_metrics_manual = {
    "accuracy": accuracy_score(y_true_mbert, y_pred_mbert),
    "attack_precision": precision_arr_mbert[0],
    "attack_recall": recall_arr_mbert[0],
    "attack_f1": f1_arr_mbert[0],
    "support_precision": precision_arr_mbert[1],
    "support_recall": recall_arr_mbert[1],
    "support_f1": f1_arr_mbert[1],
    "macro_f1": (f1_arr_mbert[0] + f1_arr_mbert[1]) / 2,
    "threshold": manual_threshold
}

print("Summary metrics for mBERT:")
print(mbert_summary_metrics_manual)

cm_mbert = confusion_matrix(y_true_mbert, y_pred_mbert)

plt.figure(figsize=(5, 4))
sns.heatmap(
    cm_mbert,
    annot=True,
    fmt="d",
    cmap=sns.light_palette("pink", as_cmap=True),
    xticklabels=["Attack", "Support"],
    yticklabels=["Attack", "Support"]
)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title(f"mBERT Confusion Matrix, threshold = {manual_threshold:.2f}")
plt.tight_layout()
plt.show()